package cangwang.com.base.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cangwang.com.base.greenDao.SettingsInfo;

import cangwang.com.base.greenDao.SettingsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig settingsInfoDaoConfig;

    private final SettingsInfoDao settingsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        settingsInfoDaoConfig = daoConfigMap.get(SettingsInfoDao.class).clone();
        settingsInfoDaoConfig.initIdentityScope(type);

        settingsInfoDao = new SettingsInfoDao(settingsInfoDaoConfig, this);

        registerDao(SettingsInfo.class, settingsInfoDao);
    }
    
    public void clear() {
        settingsInfoDaoConfig.clearIdentityScope();
    }

    public SettingsInfoDao getSettingsInfoDao() {
        return settingsInfoDao;
    }

}
